DepremAnalizSistemi/Models/Depremler.cs
namespace DepremAnalizSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Depremler")]
    public partial class Depremler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Depremler()
        {
            Mesajlar = new HashSet<Mesajlar>();
        }

        public int Id { get; set; }

        public DateTime? DepremTarihi { get; set; }

        [StringLength(100)]
        public string DepremYeri { get; set; }

        [Column(TypeName = "money")]
        public decimal? Enlem { get; set; }

        [Column(TypeName = "money")]
        public decimal? Boylam { get; set; }

        [Column(TypeName = "money")]
        public decimal? Siddet { get; set; }

        [Column(TypeName = "money")]
        public decimal? Derinlik { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesajlar> Mesajlar { get; set; }
    }
}

DepremAnalizSistemi/Controllers/DepremlerController.cs
using DepremAnalizSistemi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using DepremAnalizSistemi.Models.ViewModel;

namespace DepremAnalizSistemi.Controllers
{
    public class DepremlerController : Controller
    {
        DepremModel db = new DepremModel();
        static List<string> parantezsizDepremYerleri; //kandlliden verileri çekerken bazı yerlerin parantezli bazılarının parantezsiz olmasından dolayı parantezsizleri bu lis te tuttum.
        // GET: Depremler

        public ActionResult Index()
        {
            Helpers.MailSendHelper.Gonder("merhaba mehdi", "programa hoş geldin", "mehdi.sel.94@gmail.com");
            return View();
        }
        [HttpPost]
        public ActionResult Index(List<Depremler> data, int page = 1)
        {
            
            List<Depremler> depremler = new List<Depremler>();
            foreach (var item in db.Depremler)
            {
                if (data != null)
                {
                    if (data.Any(x => x.Id == item.Id))
                    {
                        depremler.Add(item);
                    }
                }
                else
                {
                    break;
                }
            }
           
            return Request.IsAjaxRequest()
            ? (ActionResult)PartialView("DepremTablo", depremler.OrderByDescending(x => x.DepremTarihi).ToPagedList(page, 10))
            : View(depremler.OrderByDescending(x => x.DepremTarihi).ToPagedList(page, 10));
        }

        [HttpPost]
        public JsonResult GetEarthQuakes([Bind(Include = "DepremYeri,BaslangicTarihi,BitisTarihi,MinSiddet,MaxSiddet,MinDerinlik,MaxDerinlik,Enlem,Boylam")] DepremViewModel depremViewModel)//kriterlere göre depremleri getiren ana action
        {
            List<Depremler> depremler;
            depremler = db.Depremler.Where(x => (x.DepremTarihi >= depremViewModel.BaslangicTarihi && x.DepremTarihi <= depremViewModel.BitisTarihi)&&(x.Siddet>=depremViewModel.MinSiddet&&x.Siddet<=depremViewModel.MaxSiddet)&&(x.Derinlik>=depremViewModel.MinDerinlik&&x.Derinlik<=depremViewModel.MaxDerinlik)).OrderBy(x => x.Siddet).ToList();
            if (depremViewModel.Enlem != null && depremViewModel.Boylam != null)
            {
                decimal? EnlemPY=depremViewModel.Enlem+ 0.09009009009M;
                decimal? EnlemNY=depremViewModel.Enlem- 0.09009009009M;
                decimal? BoylamPY=depremViewModel.Boylam+ 0.11764705882M;
                decimal? BoylamNY=depremViewModel.Boylam- 0.11764705882M;
                depremler = depremler.Where(x => (x.Enlem < EnlemPY && x.Enlem > EnlemNY)&&(x.Boylam<BoylamPY&&x.Boylam>BoylamNY)).ToList();
            }
            else if (depremViewModel.DepremYeri != "seciniz")//deprem yeri seçiniz değil ise ve
            {
                if (!parantezsizDepremYerleri.Contains(depremViewModel.DepremYeri))  //depremyeri parantezsizDepremYerleri içinde yok ise
                {
                    depremler = depremler.Where(x=>x.DepremYeri.Contains("(" + depremViewModel.DepremYeri + ")")).OrderBy(x => x.Siddet).ToList(); //parantezli olarak veritabanında uyuşan baslangıç ve bitiş tarihleri arasındaki verileri linq sorgusunda getirdim.
                }
                else
                {
                    depremler = depremler.Where(x =>x.DepremYeri.Contains(depremViewModel.DepremYeri)).OrderBy(x => x.Siddet).ToList();//deprem yeri seciniz değil ise ve  parantezsizDepremYerleri içinde var ise veritabanındaki baslangıç ve bitiş tarihleri arasındaki verileri linq sorgusunda getirdim.
                }
            }

            return Json(depremler.Select(x=> new { x.Id,x.DepremTarihi,x.DepremYeri,x.Boylam,x.Derinlik,x.Enlem,x.Siddet}));

        }
        [HttpGet]
        public ActionResult GetFirstAndLastRecord()//ilk ve son depremi getiren action
        {
            List<Depremler> depremler = new List<Depremler>();
            Depremler ilkDeprem = db.Depremler.OrderBy(x => x.DepremTarihi).Take(1).FirstOrDefault();//ilk depremi getiren sorgu
            depremler.Add(ilkDeprem);
            Depremler sonDeprem = db.Depremler.OrderByDescending(x => x.DepremTarihi).Take(1).FirstOrDefault();//son depremi getiren sorgu
            depremler.Add(sonDeprem);
            return Json(depremler.Select(x=>new {x.DepremTarihi }), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetCityNames(DateTime baslangicTarihi, DateTime bitisTarihi/*List<Depremler> gelenVeri*/)//baslangic ve bitis tarihine göre depremlerin oldugu yerleri getiren action
        {

            // JsonConvert.DeserializeObject<List<Depremler>>(GetEarthQuakes(baslangicTarihi, bitisTarihi).Data.ToString());

            List<Depremler> depremYeriListesi = new List<Depremler>();
            parantezsizDepremYerleri = new List<string>();
            List<Depremler> depremYerleri = db.Depremler.Where(x => x.DepremTarihi >= baslangicTarihi && x.DepremTarihi <= bitisTarihi).OrderBy(x => x.DepremYeri).ToList();//deprem yerine göre ascending sıralanmış depremler

            //var depremYerleri = db.Depremler.Select(x => new { x.DepremYeri }).Distinct();
            Depremler deprem;
            //if (gelenVeri==null)
            //{
            //    return null;
            //}
            foreach (var item in depremYerleri)//gelen depremlerin yerlerinin isimlendirilmesinin içinde deprem yerleri oldugu için gelen veriyi foreach ile dönüp istediğim şekilde parçalayıp aldım.
            {
                deprem = new Depremler();
                if (item.DepremYeri.Split('(', ')').Count() > 1)
                {
                    if (item.DepremYeri.Split('(', ')')[1].IndexOf(":") > 0)
                    {
                        deprem.DepremYeri = item.DepremYeri.Split('(', ')', ' ')[0].Trim();

                    }
                    else
                    {
                        deprem.DepremYeri = item.DepremYeri.Split('(', ')')[1].Trim();
                    }
                }
                else
                {
                    deprem.DepremYeri = item.DepremYeri.Trim();
                    parantezsizDepremYerleri.Add(deprem.DepremYeri);
                }
                depremYeriListesi.Add(deprem);
            }
            return Json(depremYeriListesi.Select(x => new { x.DepremYeri }).Distinct().OrderBy(x => x.DepremYeri), JsonRequestBehavior.AllowGet);
            //return Json(gelenVeri, JsonRequestBehavior.AllowGet); ;
        }
    }
}

DepremAnalizSistemi/Controllers/KullanicilarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DepremAnalizSistemi.Helpers;
using DepremAnalizSistemi.Models;
using DepremAnalizSistemi.Models.ViewModel;

namespace DepremAnalizSistemi.Controllers
{
    public class KullanicilarController : Controller
    {
        private DepremModel db = new DepremModel();


        public ActionResult Index()
        {
            return View(db.Kullanicilar.ToList());
        }



        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Ad,Soyad,TcNo,Email,Telefon,Sifre,SifreOnay")] Kullanicilar kullanicilar)
        {
            kullanicilar.ErrorMessage = "";
            bool emailVarMi = db.Kullanicilar.Any(x => x.Email == kullanicilar.Email);
            bool tcNoVarMi = db.Kullanicilar.Any(x => x.TcNo == kullanicilar.TcNo);
            bool telefonVarMi = db.Kullanicilar.Any(x => x.Telefon == kullanicilar.Telefon);
            if (ModelState.IsValid)
            {
                if (emailVarMi || tcNoVarMi || telefonVarMi)
                {
                    string olanlar = string.Format($"{(emailVarMi ? "Email " : "")} {(tcNoVarMi ? " Tcno " : "")} {(telefonVarMi ? "Telefon " : "")}");

                   
                    kullanicilar.ErrorMessage += olanlar + " sistemde kayıtlı.";
                    return PartialView(@"~\Views\Depremler\RegisterPartial.cshtml", kullanicilar);
                }
                db.Kullanicilar.Add(kullanicilar);
                db.SaveChanges();
                return Json(new { url = Url.Action("Index", "Depremler") });

            }
            return PartialView(@"~\Views\Depremler\RegisterPartial.cshtml", kullanicilar);
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "Email,Password")] UserLoginViewModel userLoginViewModel)
        {
            if (ModelState.IsValid)
            {
                Kullanicilar user = db.Kullanicilar.Where(x => x.Email == userLoginViewModel.Email && x.Sifre == userLoginViewModel.Password).FirstOrDefault();

                if (user != null)
                {
                    Session["kullanici"] = user.ID;
                    return Json(new { url = Url.Action("Index", "Depremler") });
                }
                else
                {
                    //bu durumda model valid ama bilgiler uyuşmuyor
                    userLoginViewModel.LoginErrorMessage = "E-posta ve şifre uyuşmuyor";
                    userLoginViewModel.Password = null;
                    return PartialView(@"~\Views\Depremler\LoginPartial.cshtml", userLoginViewModel);

                }
            }
            else
            {
                return PartialView(@"~\Views\Depremler\LoginPartial.cshtml", userLoginViewModel);
            }
        }
        public ActionResult ForgetPassword()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ForgetPassword([Bind(Include = "Email,Password")] UserLoginViewModel userLoginViewModel)
        {
            if (ModelState.IsValid)
            {
                Kullanicilar user = db.Kullanicilar.Where(x => x.Email == userLoginViewModel.Email).FirstOrDefault();

                if (user != null)
                {
                    string icerik = string.Format($"Email:{user.Email}\nŞifre:{user.Sifre}");
                    bool GonderdiMi = MailSendHelper.Gonder("Deprem Analiz Sistemi Şifre Hatırlatma", icerik, user.Email);
                    return GonderdiMi ? Json(new { url = Url.Action("Index", "Depremler") }) : (ActionResult)PartialView("PasswordPartial");
                }
                else
                {

                    return PartialView("PasswordPartial");
                }
            }
            else
            {
                return PartialView("PasswordPartial");
            }
        }
        public ActionResult Cikis()
        {
            Session.Clear();
            Session.Abandon();
            return RedirectToAction("Index", "Depremler");
        }
        [HttpPost]
        public ActionResult GetUser()
        {
            int userID = Convert.ToInt32(Session["kullanici"]);
            Kullanicilar girisYapan = db.Kullanicilar.Find(userID);
            girisYapan.Sifre = null;
            return PartialView(@"~\Views\Depremler\AccountPartial.cshtml", girisYapan);
        }
        [HttpPost]
        public ActionResult GetUsers(string Arama)
        {
            if (Session["kullanici"] == null)
            {
                return Json(null);
            }
            int kullaniciID = (int)Session["kullanici"];
            List<Kullanicilar> kullanicilar;
            kullanicilar = db.Kullanicilar.Where(x => x.ID != kullaniciID).ToList();
            List<UserViewModel> users = new List<UserViewModel>();
            UserViewModel user;
            foreach (var kullanici in kullanicilar)
            {
                user = new UserViewModel();
                user.ID = kullanici.ID;
                user.AdSoyad = (kullanici.Ad + " " + kullanici.Soyad).ToUpper();
                user.Email = kullanici.Email;
                users.Add(user);
            }
            if (!string.IsNullOrEmpty(Arama))
            {
                users = users.Where(x => x.AdSoyad.Contains(Arama.ToUpper())).ToList();

            }
            return Json(users);

        }
        [HttpPost]
        public ActionResult SendMessage([Bind(Include = "AliciID,GonderenID,DepremID,Mesaj,MesajBasligi")]Mesajlar message)
        {
            int kullaniciID = (int)Session["kullanici"];
            Mesajlar mesaj = new Mesajlar();
            mesaj.AliciID = message.AliciID;
            mesaj.DepremID = message.DepremID;
            mesaj.GonderenID = kullaniciID;
            mesaj.MesajBasligi = message.MesajBasligi;
            mesaj.Mesaj = message.Mesaj;
            mesaj.GonderimZamani = DateTime.Now;
            mesaj.GonderenSildiMi = false;
            mesaj.AliciSildiMi = false;
            mesaj.OkunduMu = false;
            db.Mesajlar.Add(mesaj);
            db.SaveChanges();
            return Json("başarılı");
        }
        [HttpPost]
        public ActionResult GetInbox()
        {
            int kullaniciID = (int)Session["kullanici"];
            return PartialView(@"~\Views\Depremler\MessagesPartial.cshtml", db.Mesajlar.Where(x => x.AliciID == kullaniciID && x.AliciSildiMi == false).OrderByDescending(x => x.GonderimZamani).ToList());
        }
        [HttpPost]
        public ActionResult GetSendMessages()
        {
            int kullaniciID = (int)Session["kullanici"];
            return PartialView(@"~\Views\Depremler\SendMessagesPartial.cshtml", db.Mesajlar.Where(x => x.GonderenID == kullaniciID && x.GonderenSildiMi == false).OrderByDescending(x => x.GonderimZamani).ToList());
        }
        [HttpPost]
        public ActionResult DeleteMessage(int MesajID)
        {
            int kullaniciID = (int)Session["kullanici"];
            Mesajlar mesaj = db.Mesajlar.Where(x => x.ID == MesajID).FirstOrDefault();
            if (mesaj.AliciID == kullaniciID)
            {
                mesaj.AliciSildiMi = true;
            }
            else if (mesaj.GonderenID == kullaniciID)
            {
                mesaj.GonderenSildiMi = true;
            }
            db.SaveChanges();
            return Json("Başarılı");
        }
        [HttpPost]
        public ActionResult GetMessage(int MesajID)
        {
            int kullaniciID = (int)Session["kullanici"];
            Mesajlar mesaj = db.Mesajlar.Where(x => x.ID == MesajID).FirstOrDefault();
            mesaj.OkunduMu = true;
            db.SaveChanges();
            if (mesaj.AliciID == kullaniciID)
            {
                var _mesaj = db.Mesajlar.Where(x => x.ID == MesajID).Select(x => new { x.ID, x.MesajBasligi, x.GonderimZamani, x.Mesaj, x.GonderenID, x.AliciID, x.Gonderen.Ad, x.Gonderen.Soyad, x.Gonderen.Email, x.Depremler.Id, x.Depremler.DepremTarihi, x.Depremler.DepremYeri, x.Depremler.Siddet, x.Depremler.Derinlik, x.Depremler.Enlem, x.Depremler.Boylam }).FirstOrDefault();
                
                return Json(_mesaj);
            }
            else
            {
                var _mesaj = db.Mesajlar.Where(x => x.ID == MesajID).Select(x => new { x.ID, x.MesajBasligi, x.GonderimZamani, x.Mesaj, x.GonderenID, x.AliciID, x.Alici.Ad, x.Alici.Soyad, x.Alici.Email, x.Depremler.Id, x.Depremler.DepremTarihi, x.Depremler.DepremYeri, x.Depremler.Siddet, x.Depremler.Derinlik, x.Depremler.Enlem, x.Depremler.Boylam }).FirstOrDefault();
                return Json(_mesaj);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeUserSettings([Bind(Include = "ID,Email,Telefon")]AccountSettingsViewModel kullanici)
        {
            bool emailVarMi = db.Kullanicilar.Any(x => x.Email == kullanici.Email && x.ID != kullanici.ID);
            bool telefonVarMi = db.Kullanicilar.Any(x => x.Telefon == kullanici.Telefon && x.ID != kullanici.ID);
            Kullanicilar bilgileriDegisecekOlanKullanici = db.Kullanicilar.Find(kullanici.ID);
            if (ModelState.IsValid)
            {
                if (emailVarMi || telefonVarMi)
                {
                    string olanlar = string.Format($"{(emailVarMi ? "Email " : "")} {(telefonVarMi ? "Telefon " : "")}");

                    // return Json(kullanicilar,JsonRequestBehavior.AllowGet);
                    bilgileriDegisecekOlanKullanici.ErrorMessage += olanlar + " sistemde kayıtlı.";

DepremAnalizSistemi/Views/Depremler/AccountPartial.cshtml
@model DepremAnalizSistemi.Models.Kullanicilar


@if (Model != null)
{
    using (Ajax.BeginForm("ChangeUserSettings", "Kullanicilar", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "MyAccountSettings", OnSuccess = "onChangeSettingsSuccess" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4 style="color:white">Bilgileri Düzenle</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    <span class="text-warning">@Html.DisplayFor(model => model.ErrorMessage)</span>
    <div class="form-group">
        @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control", @readonly = "true", autocomplete = "off" } })
            @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Soyad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Soyad, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
            @Html.ValidationMessageFor(model => model.Soyad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TcNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TcNo, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
            @Html.ValidationMessageFor(model => model.TcNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
    }


}
@if (Model != null)
{
    using (Ajax.BeginForm("ChangePassword", "Kullanicilar", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "MyAccountSettings", OnSuccess = "onChangePasswordSuccess" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4 style="color:white">Şifre Değiştir</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    <span class="text-warning">@Html.DisplayFor(model => model.PasswordErrorMessage)</span>
    <div class="form-group">
        @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2", value = "" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YeniSifre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YeniSifre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YeniSifre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YeniSifreOnay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YeniSifreOnay, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YeniSifreOnay, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
    }


}

DepremAnalizSistemi/Views/Depremler/DepremTablo.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<DepremAnalizSistemi.Models.Depremler>

@if (Model != null)
{
    <table class="table table-bordered">
        <tr>
            <th>Tarihi</th>
            <th>Yeri</th>
            <th>Enlem</th>
            <th>Boylam</th>
            <th>Şiddet</th>
            <th>Derinlik</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <th><a style="cursor:pointer" id="@item.Id" class="markerPan">@item.DepremTarihi</a></th>
                <th>@item.DepremYeri</th>
                <th>@item.Enlem</th>
                <th>@item.Boylam</th>
                <th>@item.Siddet.Value.ToString("0.0").Replace(',', '.')</th>
                <th>@item.Derinlik.Value.ToString("0.0km").Replace(',', '.')</th>
            </tr>
        }
    </table>
    <div class="sayfaNumaralari">
        @Html.PagedListPager(Model, page => Url.Action("Index", "Depremler", new { page = page }))

    </div>

}

DepremAnalizSistemi/Views/Depremler/LoginPartial.cshtml
@model DepremAnalizSistemi.Models.ViewModel.UserLoginViewModel

@using (Ajax.BeginForm("Login", "Kullanicilar", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "Login", OnSuccess = "onSuccessLogin", OnFailure = "onFailLogin" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="row">
            <div class="col-lg-offset-1 col-md-10">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="row">
            <div class="col-lg-offset-1 col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-lg-offset-1 col-md-10">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="row">
            <div class="col-lg-offset-1 col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", id = "SifreInput", autocomplete = "off"} })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                <span class="text-warning">@Html.DisplayFor(model => model.LoginErrorMessage)</span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-8 col-md-4">
            <input type="submit" value="Login" class="btn btn-default" />

        </div>
    </div>
    <a id="ForgetPass" href="#">Lost your password?</a>

}

DepremAnalizSistemi/Views/Depremler/PasswordPartial.cshtml
@model DepremAnalizSistemi.Models.ViewModel.UserLoginViewModel

@using (Ajax.BeginForm("ForgetPassword", "Kullanicilar", new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "ForgetPassword", OnSuccess = "onSuccessLostPassword", OnFailure = "onFailLostPassword" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="row">
            <div class="col-lg-offset-1 col-md-10">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="row">
            <div class="col-lg-offset-1 col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", id = "EMailInput" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <input type="text" name="Password" value="bos" hidden/>
    <div class="form-group">
        <div class="col-lg-offset-6 col-md-6">
            <input type="submit" value="Şifreyi Gönder" class="btn btn-default" />

        </div>
    </div>
}